name: CI Build for Docker Action
on:
  push:
    branches: [ main ]
    paths: [ hello-world-docker-action/** ]
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Run my own container action
        id: hello-action
        uses: dzeyelid-ghost/hello-world-docker-action2@v1
        with:
          who-to-greet: '@dzeyelid-ghost'

      - name: Output time set in the container
        run: echo "The time was ${{ steps.hello-action.outputs.time }} when the action said hello"
